spring:
  kafka:
    bootstrap-servers: localhost:9092
kafka:
   topic:
    dummy: dummy.t
km4city:
  base_url: http://servicemap.km4city.org/WebAppGrafo/api/v1/
  services:
    parkings:
      - http://www.disit.org/km4city/resource/RT04801702315PO
      - http://www.disit.org/km4city/resource/79b7b7df3f955ea9cbff956a14226218
      - http://www.disit.org/km4city/resource/RT04801700185PO
    